### ISSUE TITLE
Outcome Message should not be generated for CDISC rules

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#3]
At least for this iteration, we should not be generating outcome message from the cdisc sdtm spreadsheet. In many cases, they are incorrect.

Example
UID: 279315bb-36af-4c3f-a809-d2aa9adb8463

```yaml
Outcome:
  Message: ' and Variables are ordered with Identifiers first, followed by the Topic,
    Qualifier, and Timing variables. Within each role, variables are ordered as shown
    in SDTM tables in sections 3.1.1, 3.1.2, 3.1.3, 3.1.3.1, 3.1.4, and 3.1.5'
```

**Comment by htu** [comment]
Do you have Rule ID of this document? I have fixed the issue and would like to run a test.

**Comment by htu** [comment]
Could not find this UID in the rule editor. I set it to empty string when there is no Outcome.

**Comment by gerrycampion** [comment]
Strange, I guess the rule was deleted recently.
However, there is still an issue because now Outcome is getting overwritten with empty string. Here is a new example:
id: 0588b8b5-d903-4357-9b7d-c07df40e0cce
Rule id: CG0112

**Comment by htu** [comment]
This has been fixed in v0.4.1
